app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_assetic:
    resource: .
    type:     assetic

_security_login:
    pattern:  /admin/login
    defaults: { _controller: AppBundle:Auth:login }

_login_check:
    path: /login_check

_security_logout:
    pattern:  /logout