#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        AppBundle\Entity\User: plaintext
#            algorithm: sha512
#            encode-as-base64: true
#            iterations: 10

    role_hierarchy:
        ROLE_USER: [JOURNAL_SHOW, POST_SHOW]

    providers:
        main:
            chain:
                providers: user
        user:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        everything:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }